# Generated by Django 2.2.4 on 2022-06-28 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=55)),
                ('articles', models.ManyToManyField(related_name='tags', to='final_app.Articles')),
            ],
        ),
    ]
