# Generated by Django 4.0.5 on 2022-06-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0005_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='articles',
            field=models.ManyToManyField(related_name='tags', to='final_app.articles'),
        ),
    ]
