# Generated by Django 4.0.5 on 2022-06-28 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0008_rename_article_comment_article_id_comment_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='article_id',
            new_name='articles',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='users',
        ),
    ]
