# Generated by Django 4.0.5 on 2022-06-28 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0009_rename_article_id_comment_articles_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='articles',
            new_name='post',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='users',
        ),
    ]
