# Generated by Django 4.0.5 on 2022-06-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0010_rename_articles_comment_post_remove_comment_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='Some String', max_length=80),
        ),
    ]
