# Generated by Django 4.0.5 on 2022-06-28 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0014_alter_comment_message_id_alter_comment_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='message_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user_id',
        ),
    ]
