# Generated by Django 4.0.5 on 2022-06-29 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0015_remove_comment_message_id_remove_comment_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='user_like',
        ),
        migrations.AddField(
            model_name='articles',
            name='liked',
            field=models.ManyToManyField(blank=True, default=None, related_name='liked', to='final_app.users'),
        ),
        migrations.AddField(
            model_name='comment',
            name='message_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='final_app.articles'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='final_app.users'),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('Like', 'Like'), ('Unlike', 'Unlike')], default='Like', max_length=10)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='final_app.articles')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='final_app.users')),
            ],
        ),
    ]
